# Generated by Django 2.2.7 on 2020-01-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
