# Generated by Django 2.2.9 on 2020-01-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
