# Generated by Django 2.2.7 on 2019-12-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
