# Generated by Django 2.2.7 on 2019-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_auto_20191218_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'На модерации'), (1, 'Опубликован')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'На модерации'), (1, 'Опубликован')], default=0, verbose_name='Статус'),
        ),
    ]
