# Generated by Django 2.2.7 on 2019-12-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_auto_20191218_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
