# Generated by Django 2.2.7 on 2019-12-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_auto_20191218_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
