# Generated by Django 2.2.7 on 2019-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_auto_20191218_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
