# Generated by Django 2.2.7 on 2020-01-13 10:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_auto_20191219_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='s_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=400, null=True, verbose_name='Краткое сожержимое'),
        ),
    ]
