# Generated by Django 2.2.9 on 2020-01-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0024_postparam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostParam',
        ),
    ]
