# Generated by Django 2.2.9 on 2020-01-31 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0025_delete_postparam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr1', models.TextField()),
                ('ingr2', models.TextField()),
                ('ingr3', models.TextField()),
                ('ingr4', models.TextField()),
                ('ingr5', models.TextField()),
                ('ingr6', models.TextField()),
                ('ingr7', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Post', verbose_name='Пост')),
            ],
        ),
    ]
